<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyQuanCafe" Class="qlcfDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RPPPDK0\SQLEXPRESS;Initial Catalog=QuanLyQuanCafe;Integrated Security=True" SettingsObjectName="KN.Properties.Settings" SettingsPropertyName="QuanLyQuanCafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ban" Member="Bans">
    <Type Name="Ban">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Ban_HoaDon" Member="HoaDons" ThisKey="Id" OtherKey="IdBan" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.ThucDon" Member="ThucDons">
    <Type Name="ThucDon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ThucDon_Mon" Member="Mons" ThisKey="Id" OtherKey="IdThucDon" Type="Mon" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="IdHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdMon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="IdHoaDon" OtherKey="Id" Type="HoaDon" IsForeignKey="true" />
      <Association Name="Mon_ChiTietHoaDon" Member="Mon" ThisKey="IdMon" OtherKey="Id" Type="Mon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeCheckIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeCheckOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="Id" OtherKey="IdHoaDon" Type="ChiTietHoaDon" />
      <Association Name="Ban_HoaDon" Member="Ban" ThisKey="IdBan" OtherKey="Id" Type="Ban" IsForeignKey="true" />
      <Association Name="TaiKhoan_HoaDon" Member="TaiKhoan" ThisKey="NguoiLap" OtherKey="UserName" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mon" Member="Mons">
    <Type Name="Mon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IdThucDon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Mon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="Id" OtherKey="IdMon" Type="ChiTietHoaDon" />
      <Association Name="ThucDon_Mon" Member="ThucDon" ThisKey="IdThucDon" OtherKey="Id" Type="ThucDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="UserName" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="HoatDong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhanQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_HoaDon" Member="HoaDons" ThisKey="UserName" OtherKey="NguoiLap" Type="HoaDon" />
    </Type>
  </Table>
</Database>